apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: grafana
  namespace: {{ .Release.Namespace }}
spec:
  host: grafana.{{ .Release.Namespace }}
  trafficPolicy:
    tls:
      mode: DISABLE
