{{ if .Values.clusterResources }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: istio-pilot-{{ .Release.Namespace }}
  labels:
    app: pilot
    release: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: istio-pilot-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: istio-pilot-service-account
    namespace: {{ .Release.Namespace }}
---
{{ end }}
