apiVersion: install.istio.io/v1alpha2
kind: IstioControlPlane
spec:
  security:
    components:
      nodeAgent:
        enabled: true

  values:
    global:
      controlPlaneSecurityEnabled: false
      mtls:
        enabled: true
      sds:
        enabled: true
        udsPath: "unix:/var/run/sds/uds_path"
        useNormalJwt: false
        useTrustworthyJwt: true
    nodeagent:
      image: node-agent-k8s
      env:
        # TODO: empty env vars can't be set in components.nodeagent.k8s.env above because default values are considered
        # unset. Also, the k8s settings above override these as a block, so we cannot currently set env in both places.
        Plugins: ""
        CA_ADDR: "istio-citadel:8060"
        CA_PROVIDER: Citadel
        VALID_TOKEN: "true"

