{{ $gateway := index .Values "gateways" "istio-ingressgateway" }}
{{- if .Values.global.meshExpansion.enabled }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: meshexpansion-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 15011
        protocol: TCP
        name: tcp-pilot
      hosts:
        - "*"
    - port:
        number: 8060
        protocol: TCP
        name: tcp-citadel
      hosts:
        - "*"
---

apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: meshexpansion-vs-pilot1
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
spec:
  hosts:
  - istio-pilot.{{ .Values.global.istioNamespace }}.svc.cluster.local
  gateways:
  - meshexpansion-gateway
  tcp:
  - match:
    - port: {{ $gateway.externalPort }}
    route:
    - destination:
        host: istio-pilot.{{ .Values.global.istioNamespace }}.svc.cluster.local
        port:
          number: 15011
  #  - match:
  #    - port: 53
  #    route:
  #    - destination:
  #        host: kube-dns.kube-system.svc.cluster.local
  #        port:
  #          number: 53
---

apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: meshexpansion-dr-pilot9
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
spec:
  host: istio-pilot.{{ .Release.Namespace }}.svc.cluster.local
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 15011
      tls:
        mode: DISABLE
---


apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: meshexpansion-vs-citadel
  namespace: {{ .Release.Namespace }}
  labels:
    release: {{ .Release.Name }}
spec:
  hosts:
  - istio-citadel.{{ $.Release.Namespace }}.svc.cluster.local
  gateways:
  - meshexpansion-gateway
  tcp:
  - match:
    - port: 8060
    route:
    - destination:
        host: istio-citadel.{{ $.Release.Namespace }}.svc.cluster.local
        port:
          number: 8060

{{- end }}

