apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: prometheys
  namespace: {{ .Release.Namespace }}
spec:
  host: prometheus.{{ .Release.Namespace }}
  trafficPolicy:
    tls:
      mode: DISABLE
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: prometheus-full
  namespace: {{ .Release.Namespace }}
spec:
  host: prometheus.{{ .Release.Namespace }}.svc.cluster.local
  trafficPolicy:
    tls:
      mode: DISABLE
