{{- if .Values.global.defaultPodDisruptionBudget.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: istio-telemetry
  namespace: {{ .Release.Namespace }}
  labels:
    app: istio-telemetry
    release: {{ .Release.Name }}
    istio: mixer
    istio-mixer-type: telemetry
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: istio-telemetry
      release: {{ .Release.Name }}
      istio: mixer
      istio-mixer-type: telemetry
---

{{- end }}
