{{ $gateway := index .Values "gateways" "istio-egressgateway" }}
{{- if .Values.global.defaultPodDisruptionBudget.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: istio-egressgateway
  namespace: {{ .Release.Namespace }}
  labels:
    app: istio-egressgateway
    istio: egressgateway
    release: {{ .Release.Name }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
        app: istio-egressgateway
        istio: egressgateway
        release: {{ .Release.Name }}
{{- end }}
