{{ $gateway := index .Values "gateways" "istio-egressgateway" }}
apiVersion: v1
kind: Service
metadata:
  name: istio-egressgateway
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- range $key, $val := $gateway.serviceAnnotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
  labels:
    app: istio-egressgateway
    release: {{ .Release.Name }}
spec:
  type: ClusterIP
  selector:
    app: istio-egressgateway
  ports:
    {{- range $key, $val := $gateway.ports }}
    -
      {{- range $pkey, $pval := $val }}
      {{ $pkey}}: {{ $pval }}
      {{- end }}
    {{- end }}
---
