apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istio-cni
  labels:
    app: istio-cni
    release: {{ .Release.Name }}
rules:
- apiGroups: [""]
  resources:
  - pods
  - nodes
  verbs:
  - get
