apiVersion: apps/v1
kind: Deployment
metadata:
  name: certmanager
  namespace: {{ .Release.Namespace }}
  labels:
    app: certmanager
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.certmanager.replicaCount }}
  selector:
    matchLabels:
      app: certmanager
  template:
    metadata:
      labels:
        app: certmanager
        release: {{ .Release.Name }}        
        {{- if .Values.certmanager.podLabels }}
{{ toYaml .Values.certmanager.podLabels | indent 8 }}
        {{- end }}
      annotations:
        sidecar.istio.io/inject: "false"
        {{- if .Values.certmanager.podAnnotations }}
{{ toYaml .Values.certmanager.podAnnotations | indent 8 }}
        {{- end }}
    spec:
      serviceAccountName: certmanager
{{- if .Values.global.priorityClassName }}
      priorityClassName: "{{ .Values.global.priorityClassName }}"
{{- end }}
      containers:
      - name: certmanager
        image: "{{ .Values.certmanager.hub }}/{{ .Values.certmanager.image }}:{{ .Values.certmanager.tag }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy | default "Always" }}
        args:
        - --cluster-resource-namespace=$(POD_NAMESPACE)
        - --leader-election-namespace=$(POD_NAMESPACE)
      {{- if .Values.certmanager.extraArgs }}
{{ toYaml .Values.certmanager.extraArgs | indent 8 }}
      {{- end }}
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        resources:
{{ toYaml .Values.certmanager.resources | indent 10 }}
      {{- if .Values.certmanager.podDnsPolicy }}
      dnsPolicy: {{ .Values.certmanager.podDnsPolicy }}
      {{- end }}
      {{- if .Values.certmanager.podDnsConfig }}
      dnsConfig:
{{ toYaml .Values.certmanager.podDnsConfig | indent 8 }}
      {{- end }}
      affinity:
      {{- include "nodeaffinity" . | indent 6 }}
      {{- include "podAntiAffinity" . | indent 6 }}
{{- if .Values.certmanager.tolerations }}
      tolerations:
{{ toYaml .Values.certmanager.tolerations | indent 6 }}
{{- end }}
