{{- if .Values.global.defaultPodDisruptionBudget.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: certmanager
  namespace: {{ .Release.Namespace }}
  labels:
    app: certmanager
    release: {{ .Release.Name }}
    {{- if .Values.certmanager.podLabels }}
{{ toYaml .Values.certmanager.podLabels | indent 4 }}
    {{- end }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: certmanager
      release: {{ .Release.Name }}
{{- end }}
